services:
  # Backend API Service
  - type: web
    name: aspireai-backend
    env: node
    plan: free
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false

  # Frontend Static Site  
  - type: static
    name: aspireai-frontend
    env: static
    plan: free
    rootDir: ./client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://aspireai-backend.onrender.com