services:
  # Backend API Service
  - type: web
    name: aspireai-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: aspireai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false

  # Frontend Static Site
  - type: static
    name: aspireai-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://aspireai-backend.onrender.com

databases:
  - name: aspireai-db
    databaseName: aspireai
    user: aspireai_user